version: '3.8'

services:
  test-backend:
    image: jonathanhuertascontreras/test-backend
    container_name: container-test-backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge 