name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Borrar imagen local previa (si existe)
        run: |
          docker rmi jonathanhuertascontreras/test-backend || true

      - name: Build imagen Docker
        run: |
          docker build -f Dockerfile.prod -t jonathanhuertascontreras/test-backend .

      - name: Push imagen a DockerHub
        run: |
          docker push jonathanhuertascontreras/test-backend

      - name: Mostrar información de la imagen
        run: |
          echo "✅ Imagen subida exitosamente: jonathanhuertascontreras/test-backend"
          echo "📦 Para ejecutar localmente:"
          echo "   docker pull jonathanhuertascontreras/test-backend"
          echo "   docker run -p 3000:3000 jonathanhuertascontreras/test-backend"
          echo "   # O con docker compose:"
          echo "   docker compose up -d"